language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: 0c2d93484064a96078a0545605c1990bc9259fad    
  keep_history: true
  on:
    branch: master  